steps:
- name: 'gcr.io/cloud-builders/npm'
  id: installing_npm
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  id: building_with_npm
  args: ['run','build']
  

- name: 'gcr.io/cloud-builders/npm'
  id: unit_testing
  args: ['install','-g','karma-cli','run','test']
 # args: ['install','-g','karma-cli','run','test','--','code-coverage','no-watch','no-progress','browsers=ChromeHeadlessNoSandbox']
  
- id: 'SonarQube analysis'
  name: 'gcr.io/$PROJECT_ID/sonarcloud-scanner'
  args:
  - '-Dsonar.host.url=https://sonarcloud.io/'
  - '-Dsonar.login=8f13e08c78c3dac5fa9836533358c19de98f32fd'
  - '-Dsonar.oranization=lttsd'
  - '-Dsonar.projectKey=lttsd_sample-nodejs-project'
  - '-Dsonar.projectVersion=1.0'
  - '-Dsonar.language=js'
  - '-Dsonar.sourceEncoding=UTF-8'
  - '-Dsonar.sources=src'
  - '-Dsonar.exclusions=**/node_modules/**'
  - '-Dsonar.tests=src'
  - '-Dsonar.test.inclusions=**/*.test.js'
  - '-Dsonar.typescript.lcov.reportPaths=coverage/lcov.info'
  - '-Dsonar.testExecutionReportPaths=test-report.xml'
  tags: ['cloud-builders-community']
  
#- name: 'gcr.io/cloud-builders/npm'
 # id: building_application
  #args: ['run','build']

#- name: 'gcr.io/cloud-builders/npm'
 # id: sonarpush
  #args: ['install','-D','sonarqube-scanner','run','test','sonar-scanner']
  

- name: 'gcr.io/cloud-builders/docker'
  id: building_image_using_docker
  args: ["build", "-t", "gcr.io/$PROJECT_ID/nodej:$COMMIT_SHA", "-t", "gcr.io/$PROJECT_ID/nodej:latest", "."]
- name: 'gcr.io/cloud-builders/docker'
  id: pushing_image_gcr
  args: ["push", "gcr.io/$PROJECT_ID/nodej:$COMMIT_SHA"]
- name: 'gcr.io/cloud-builders/docker'
  id: pushing_container_image_gke
  args: ["push", "gcr.io/$PROJECT_ID/nodej:latest"]
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  id: deploying_container_gke
  args:
  - run
  - --image=gcr.io/$PROJECT_ID/nodej:latest
  - --location=asia-east1-a
  - --cluster=tf-gke-cluster
  - --app=nodej
  - --expose=8080
  - --namespace=default
options:
    machineType: 'N1_HIGHCPU_8'