steps:
- name: 'gcr.io/cloud-builders/npm'
  id: installing_npm
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  id: building_with_npm
  args: ['run','build']


- name: 'gcr.io/cloud-builders/npm'
  id: unit_testing
  args: ['install','-g','karma-cli','run','test']
 
 # args: ['install','-g','karma-cli','run','test','--','code-coverage','no-watch','no-progress','browsers=ChromeHeadlessNoSandbox']
- name: 'gcr.io/cloud-builders/npm'
  id: install sonar-scanner 
  args: ['install','sonarqube-scanner']
  
- name: 'gcr.io/cloud-builders/npm'
  id: install typescript 
  args: ['install','-D','typescript@latest']
  
- name: 'gcr.io/cloud-builders/npm'
  id: sonarpush
  args: ['run','sonar']  

- name: 'gcr.io/cloud-builders/docker'
  id: building_image_using_docker
  args: ["build", "-t", "gcr.io/$PROJECT_ID/nodej:$COMMIT_SHA", "-t", "gcr.io/$PROJECT_ID/nodej:latest", "."]
- name: 'gcr.io/cloud-builders/docker'
  id: pushing_image_gcr
  args: ["push", "gcr.io/$PROJECT_ID/nodej:$COMMIT_SHA"]
- name: 'gcr.io/cloud-builders/docker'
  id: pushing_container_image_gke
  args: ["push", "gcr.io/$PROJECT_ID/nodej:latest"]
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  id: deploying_container_gke
  args:
  - run
  - --image=gcr.io/$PROJECT_ID/nodej:latest
  - --location=us-east4-c
  - --cluster=standard-cluster-1
  - --app=nodej
  - --expose=8080
  - --namespace=default
options:
    machineType: 'N1_HIGHCPU_8'