steps:

- name: 'gcr.io/cloud-builders/docker'

  args: ['build', '--tag=gcr.io/$PROJECT_ID/base', '.']



# Print Node.js version.

- name: 'gcr.io/$PROJECT_ID/base'

  entrypoint: 'node'

  args: ['--version']

- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']



# Print repo-tools version.

- name: 'gcr.io/$PROJECT_ID/base'

  entrypoint: 'repo-tools'

  args: ['--version']



images: ['gcr.io/$PROJECT_ID/base']